### ISSUE TITLE
questions about the versions of python and numpy

### ISSUE THREAD

**Issue by YuhangXiao1103** [yysun0116/AI4ACP#1]
* The Python version is: Python3.7 from "D:\Anaconda\envs\ai4acp\python.exe"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: 找不到指定的模块。

Above is the failed issue.
Can anyone tell what the versions of python and numpy in this task?
Or show the "requirements.txt".
Please!

**Comment by yysun0116** [comment]
Hi @Gryff1ndor 
Sorry for the late reply,
AI4ACP was built on Python3.6, TensorFlow version 2.3; therefore the Numpy version required should be <1.19.0, >=1.16.0.
Thanks for your feedback!

**Comment by YuhangXiao1103** [comment]
Thank you so much!!!



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/19/2023 11:47 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [yysun0116/AI4ACP] questions about the versions of python and numpy (Issue #1) |

Hi @Gryff1ndor
Sorry for the late reply,
AI4ACP was built on Python3.6, TensorFlow version 2.3; therefore the Numpy version required should be <1.19.0, >=1.16.0.
Thanks for your feedback!
